/*----------------------------------------------------------------------------*/
/* Copyright (c) 2022 Team 501 - The PowerKnights. All Rights Reserved.       */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the 2022 Team 501 - The PowerKnights BSD license    */
/* file in the root directory of the project.                                 */
/*----------------------------------------------------------------------------*/

// WARNING: This file is automatically generated in build.gradle
package frc.robot.config;

/**
 * This class provides a versioning string that can be used to determine the
 * build pedigree of a robot as loaded on the roboRIO.
 * <p>
 * Unfortunately, Git doesn't provide a way to automate this the way other CM
 * tools do with keyword expansions.
 **/
public class CodeVersionInfo {
    public static final String programmer = "Matt Gleich";
    public static final String commitSHA = "0521ab8";
    public static final String timeStamp = "20220115 120232";

    public static final String version = "501-Robot 0521ab8 20220115 120232 Matt Gleich";
}
